FILTER = {
    "Card Type": [
        "Normal",
        "Effect",
        "Fusion",
        "Ritual",
        "Synchro",
        "Xyz",
        "Pendulum",
        "Link",
        "Spell",
        "Trap",
    ],
    "Attribute": [
        "LIGHT",
        "DARK",
        "WATER",
        "FIRE",
        "EARTH",
        "WIND",
        "DIVINE",
    ],
    "Type of Spell and Trap": [
        "Normal Spell",
        "Field Spell",
        "Equip Spell",
        "Continuous Spell",
        "Quick-play Spell",
        "Ritual Spell",
        "Normal Trap",
        "Continuous Trap",
        "Counter Trap",
    ],
    "Type": [
        "Spellcaster",
        "Dragon",
        "Zombie",
        "Warrior",
        "Beast-Warrior",
        "Beast",
        "Winged Beast",
        "Machine",
        "Fiend",
        "Fairy",
        "Insect",
        "Dinosaur",
        "Reptile",
        "Fish",
        "Sea Serphent",
        "Aqua",
        "Pyro",
        "Thunder",
        "Rock",
        "Plant",
        "Psychic",
        "Wyrm",
        "Cyberse",
        "Divine-Beast",
        "Illusion",
    ],
    "Level/Rank/Link": [str(i) for i in list(range(14))],  # 0 - 13
    "Abilities/Other": [
        "Toon",
        "Gemini",
        "Union",
        "Spirit",
        "Tuner",
        "Flip",
        "Special Summon",
    ],
    "Limit": [
        "Forbidden",
        "Limited",
        "Semi-Limited",
        "Unlimited",
    ],
}
